### ISSUE TITLE
sorry newb problem

### ISSUE THREAD

**Issue by jmrphy** [papplication/alice#1]
Couldn't get this working, it can't find modules? Downloaded, confirmed I have node, ran 'node alice.js' from main directory and it can't find module ".../alice/alice.js"? I updated node, tried installing it a few different ways, API keys are definitely right, am I missing something obvious?

**Comment by kmoe** [comment]
You need to run `node alice.js` from inside the `src` directory.

Unfortunately, when you do that, it will throw an error saying `Error: Cannot find module '../settings_alice.js'`. That's because `src/libs/wrapper.js` is trying to find the file `../settings_alice.js`, which doesn't exist. 

So you need to change line 2 in `wrapper.js` to refer to `../settings.js` instead. It should then run fine - I don't have API keys so I get `401 Unauthorized` at this point.

**Comment by jmrphy** [comment]
Works, thank you!

**Comment by papplication** [comment]
Thanks guys! I fixed it, and updated the description too. I totally avoided this issue. I did not realize that there is an open issue. But now... 😄
